### PR TITLE
Updated state name add pose trajectory

### PR DESCRIPTION
**Pull request by CaroBoud**
## Description
Updated state name add_pose_trajectory for manual_add_pose_trajectory

## How has this been tested ?
This has been tested in simulation. We edited the mission to be able to use it without the mission switch. After that, we were able to test it in unity.

## Checklist
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have made corresponding changes to the documentation
- [ X ] My changes generate no new warnings

### CODE REVIEW

**Comment by S1lver-Owl** [comment]
Is it the manual or the input (automatic) state we need to use?

**Comment by CaroBoud** [comment]
> Is it the manual or the input (automatic) state we need to use?
manual_add_pose_to_trajectory, on peut lui envoyer les paramètres qu'on envoyait autrefois dans la mission soit "positionX=0, positionY=0, positionZ=1, orientationX=0, orientationY=0, orientationZ=0, frame=1, speed=0, precision=0, long_rotation=False" 
On ne peut pas envoyer ses paramètres à vision_add_pose_to_trajectory. On souhaite lui envoyer les paramètres manuellement pour le moment. 
D'ailleurs, vision_add_pose_to_trajectory est pour des états de visions seulement.

**Comment by S1lver-Owl** [comment]
Update the ChangeList (The main description at the beginning)

**Review by S1lver-Owl — COMMENTED** [review]
Looks good to me! Good for pool test first!

**Review by S1lver-Owl — APPROVED** [review]
Good!

**Pull request merged**
